<?php

return [
    'show_warnings' => false,
    'render' => env('DOMPDF_RENDER', 'html'),
    'strict' => env('DOMPDF_STRICT', false),
    'log_origin_file' => false,
    'log_origin_html' => false,
    'enable_font_subsetting' => false,
    'pdf_backend' => env('DOMPDF_PDF_BACKEND', 'CPDF'),
    'pdfa' => env('DOMPDF_PDFA', false),
    'pdfbc' => env('DOMPDF_DFBC', false),
    'dpi' => env('DOMPDF_DPI', 96),
    'default_paper_size' => env('DOMPDF_DEFAULT_PAPER_SIZE', 'a4'),
    'default_paper_orientation' => env('DOMPDF_DEFAULT_PAPER_ORIENTATION', 'portrait'),
    'default_font' => env('DOMPDF_DEFAULT_FONT', 'sans-serif'),
    'font_cache' => storage_path('fonts/'),
    'font_dir' => storage_path('fonts/'),
    'temp_dir' => sys_get_temp_dir(),
    'chroot' => realpath(base_path()),
    'allowed_protocols' => [
        'file://' => ['rules' => []],
        'http://' => ['rules' => []],
        'https://' => ['rules' => []],
    ],
    'artifact_path' => sys_get_temp_dir(),
    'log_output_file' => storage_path('logs/dompdf.html'),
    'is_remote_enabled' => env('DOMPDF_ENABLE_REMOTE', true),
    'is_php_enabled' => env('DOMPDF_ENABLE_PHP', false),
    'is_javascript_enabled' => env('DOMPDF_ENABLE_JAVASCRIPT', true),
    'debug_png' => env('DOMPDF_DEBUG_PNG', false),
    'debug_keep_temp' => env('DOMPDF_DEBUG_KEEP_TEMP', false),
    'debug_css' => env('DOMPDF_DEBUG_CSS', false),
    'debug_layout' => env('DOMPDF_DEBUG_LAYOUT', false),
    'debug_layout_lines' => env('DOMPDF_DEBUG_LAYOUT_LINES', true),
    'debug_layout_blocks' => env('DOMPDF_DEBUG_LAYOUT_BLOCKS', true),
    'debug_layout_inline' => env('DOMPDF_DEBUG_LAYOUT_INLINE', true),
    'debug_layout_padding_box' => env('DOMPDF_DEBUG_LAYOUT_PADDING_BOX', true),
    'debug_layout_border_box' => env('DOMPDF_DEBUG_LAYOUT_BORDER_BOX', true),
    'debug_layout_text_box' => env('DOMPDF_DEBUG_LAYOUT_TEXT_BOX', true),
    'admin_user' => env('DOMPDF_ADMIN_USER'),
    'admin_password' => env('DOMPDF_ADMIN_PASSWORD'),
];
